# Run Cockatrice in a container

# Base docker image
from ubuntu:14.04

# Add user: josh
run useradd josh -G audio,video 

#Add Cockatrice installation package.
add ./Cockatrice-Decked_Out_Revision_1-2.5.1.deb /home/josh/install_cockatrice.deb

# Install Cockatrice
#run apt-get update && apt-get install -y /home/josh/install_cockatrice.deb

# Run Container as josh
#user josh

# Autorun chrome
#ENTRYPOINT [ "google-chrome" ]
#CMD [ "--user-data-dir=/data" ]
